#!/usr/bin/env bash
# Create the FEM environment (D-17) in the gitignored vendor/fem-env:
# FreeCAD 1.1.3 with its FEM and CAM workbenches, Gmsh 4.15.2, CalculiX 2.23.
#
# Installs a pinned micromamba binary (checked by SHA-256), then creates the
# environment from the committed explicit lock, where every package is a
# conda-forge URL plus SHA-256. Nothing binary is committed.
#
# Usage:
#   scripts/setup_fem_env.sh            create vendor/fem-env from the lock
#   scripts/setup_fem_env.sh --relock   re-solve SPECS and rewrite the lock
#
# The install path needs only bash, curl and shasum, which ship with macOS.
# --relock also needs python3.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor"
ENV_PREFIX="$VENDOR/fem-env"
LOCK="$ROOT/env/fem-osx-arm64.lock"
MM="$VENDOR/bin/micromamba"

MM_VERSION="2.9.0-0"
MM_URL="https://github.com/mamba-org/micromamba-releases/releases/download/$MM_VERSION/micromamba-osx-arm64"
MM_SHA256="ec2a072f028e1a7cf20f3e2e74d5a8127cf5a5f27636375b5359811565f4e5be"

SPECS=("python=3.11" "freecad=1.1.3" "gmsh=4.15.2" "python-gmsh=4.15.2" "calculix=2.23" "pyvista" "ccx2paraview")

# Keep micromamba's package cache and config inside vendor/, not in $HOME.
export MAMBA_ROOT_PREFIX="$VENDOR/mamba"

die() { echo "error: $*" >&2; exit 1; }

[[ "$(uname -s)-$(uname -m)" == "Darwin-arm64" ]] || die "macOS arm64 only (D-17)"

install_micromamba() {
  if [[ -x "$MM" ]] && echo "$MM_SHA256  $MM" | shasum -a 256 -c --status; then
    return
  fi
  echo "fetch   micromamba $MM_VERSION"
  mkdir -p "$(dirname "$MM")"
  curl --fail --location --silent --show-error --retry 3 --output "$MM.part" "$MM_URL"
  echo "$MM_SHA256  $MM.part" | shasum -a 256 -c --status \
    || { rm -f "$MM.part"; die "micromamba checksum mismatch"; }
  chmod +x "$MM.part"
  mv "$MM.part" "$MM"
}

relock() {
  echo "solve   ${SPECS[*]}"
  local solve
  solve="$(mktemp)"
  "$MM" create --dry-run --yes --json --prefix "$VENDOR/solve-env" \
    --override-channels --channel conda-forge --platform osx-arm64 "${SPECS[@]}" > "$solve"
  mkdir -p "$(dirname "$LOCK")"
  python3 - "$solve" "$LOCK" "${SPECS[*]}" <<'EOF'
import json, sys
solve, lock, specs = sys.argv[1:]
pkgs = sorted(json.load(open(solve))["actions"]["LINK"], key=lambda p: p["name"])
with open(lock, "w") as f:
    f.write("# FEM environment explicit lock (D-17). Generated by scripts/setup_fem_env.sh --relock\n")
    f.write(f"# specs: {specs}\n# platform: osx-arm64\n@EXPLICIT\n")
    for p in pkgs:
        f.write(f"{p['url']}#{p['sha256']}\n")
print(f"lock    {len(pkgs)} packages -> {lock}")
EOF
  rm -f "$solve"
}

create_env() {
  [[ -f "$LOCK" ]] || die "no lock at $LOCK; run with --relock"
  echo "create  vendor/fem-env from $(basename "$LOCK")"
  rm -rf "$ENV_PREFIX"
  # GTK and graphviz post-link scripts warn loudly; nothing headless needs them.
  local log="$VENDOR/fem-env-create.log"
  "$MM" create --yes --quiet --prefix "$ENV_PREFIX" --file "$LOCK" > "$log" 2>&1 \
    || { tail -20 "$log" >&2; die "micromamba create failed; see $log"; }
  # conda-forge installs FreeCAD.so in lib/, not site-packages.
  echo "import sys, os; sys.path.append(os.path.join(sys.prefix, 'lib'))" \
    > "$ENV_PREFIX/lib/python3.11/site-packages/freecad-lib.pth"
  "$ENV_PREFIX/bin/python" -c "import FreeCAD, Fem, Path, PathSimulator, gmsh; print('ok      FreeCAD', '.'.join(FreeCAD.Version()[:3]))"
  # ccx -v prints its version but exits non-zero, so check the text only.
  local ccx_version
  ccx_version="$("$ENV_PREFIX/bin/ccx" -v 2>&1 || true)"
  [[ "$ccx_version" == *"Version 2.23"* ]] || die "ccx is not 2.23: $ccx_version"
  echo "ok      ccx 2.23"
}

install_micromamba
case "${1:-}" in
  --relock) relock ;;
  "") create_env ;;
  *) die "unknown argument: $1" ;;
esac
